name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password | docker login --username AWS --password-stdin <your-ecr-uri>

      - name: Build and Push Docker Image
        run: |
          docker build -t borda-api .
          docker tag borda-api:latest <your-ecr-uri>
          docker push 